AWSTemplateFormatVersion: "2010-09-09"
Description: Template to deploy the AI Sales Roleplay application using CodeBuild

Parameters:
  AllowSelfRegister:
    Type: String
    Default: "true"
  BedrockRegion:
    Type: String
    Default: "us-east-1"
    Description: "The AWS region where Amazon Bedrock services are available"
  CdkJsonOverride:
    Type: String
    Default: "{}"
    Description: "JSON object to override CDK configuration"
  RepoUrl:
    Type: String
    Default: "https://github.com/aws-samples/sample-ai-sales-roleplay.git"
    Description: "GitHub repository URL"
  Version:
    Type: String
    Default: "main"
    Description: "Branch or tag to deploy"

Resources:
  ProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AdministratorAccess

  ProjectRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: Project
                    - :*
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: Project
          - Action:
              - codebuild:BatchPutCodeCoverages
              - codebuild:BatchPutTestCases
              - codebuild:CreateReport
              - codebuild:CreateReportGroup
              - codebuild:UpdateReport
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":codebuild:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :report-group/
                  - Ref: Project
                  - -*
        Version: "2012-10-17"
      PolicyName: ProjectRoleDefaultPolicy
      Roles:
        - Ref: ProjectRole

  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE
      EncryptionKey: alias/aws/s3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux-x86_64-standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ALLOW_SELF_REGISTER
            Value: !Ref AllowSelfRegister
          - Name: BEDROCK_REGION
            Value: !Ref BedrockRegion
          - Name: CDK_JSON_OVERRIDE
            Value: !Ref CdkJsonOverride
          - Name: REPO_URL
            Value: !Ref RepoUrl
          - Name: VERSION
            Value: !Ref Version
      ServiceRole:
        Fn::GetAtt:
          - ProjectRole
          - Arn
      Source:
        BuildSpec: |-
          {
            "version": 0.2,
            "phases": {
              "install": {
                "runtime-versions": {
                  "nodejs": "22"
                },
                "on-failure": "ABORT",
                "commands": [
                  "echo 'Installing dependencies...'",
                  "yum update -y",
                  "yum install -y python3 jq"
                ]
              },
              "build": {
                "commands": [
                  "echo 'Build phase started...'",
                  "git clone --branch $VERSION $REPO_URL ai-sales-roleplay",
                  "cd ai-sales-roleplay",
                  "if [ \"$ALLOW_SELF_REGISTER\" = \"false\" ]; then sed -i 's/\"selfSignUpEnabled\": true/\"selfSignUpEnabled\": false/' cdk/cdk.json; fi",
                  "sed -i \"s/\\\"bedrockRegion\\\": \\\"[^\\\"]*\\\"/\\\"bedrockRegion\\\": \\\"${BEDROCK_REGION}\\\"/\" cdk/cdk.json",
                  "echo \"$CDK_JSON_OVERRIDE\" | jq '.' && jq --argjson override \"$CDK_JSON_OVERRIDE\" '. * $override' cdk/cdk.json > temp.json && mv temp.json cdk/cdk.json",
                  "cd frontend",
                  "npm ci",
                  "npm run build",
                  "cd ../cdk",
                  "npm ci",
                  "npx cdk bootstrap",
                  "npx cdk deploy --require-approval never --all"
                ]
              }
            }
          }
        Type: NO_SOURCE

Outputs:
  ProjectName:
    Value:
      Ref: Project
    Description: "CodeBuild project name"